### ISSUE TITLE
CentOS not working

### ISSUE THREAD

**Issue by TCB13** [aivarsk/multi-socks#1]
Hello,

I've been using this for a long time on Debian based servers, however today I tried it on a centos based server (actually cloudlinux) and it didn't work, I get connection reset on the browser. Curl doesn't output anything also...

Any ideias and/or how to track the issue?

Thank you!

**Comment by TCB13** [comment]
I get this under the log file:

```2015-01-18 16:48:13+0100 [twisted.plugins.multisocks_plugin.MultiSOCKSv4Factory] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib64/python2.6/site-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
	    why = getattr(selectable, method)()
	--- <exception caught here> ---
	  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 932, in doRead
	    protocol = self.factory.buildProtocol(self._buildAddr(addr))
	  File "/usr/lib/python2.6/site-packages/twisted/plugins/multisocks_plugin.py", line 42, in buildProtocol
	    return MultiSOCKSv4(self.interface, self.whitelist)
	  File "/usr/lib/python2.6/site-packages/twisted/plugins/multisocks_plugin.py", line 8, in __init__
	    SOCKSv4.__init__(self, None, reactor)
	exceptions.TypeError: __init__() takes at most 2 arguments (3 given)```

**Comment by TCB13** [comment]
This issue was caused by the old version of Python included on CentOS / CloudLinux. If anyone is have problems with those, the best option is to install a different version of Python side-by-side with the system older version (so you won't break yum or anything) and then run multi-scoks on a virtual env.

You can follow this introductions in order to get it working...

# Install a compatible Python

```
sudo yum groupinstall -y development
sudo yum install -y zlib-dev openssl-devel sqlite-devel bzip2-devel    
wget https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tgz
tar xzf Python-2.7.6.tgz
cd Python-2.7.6
./configure --prefix=/usr/local
sudo make
sudo make alt install
```

This will install a secondary Python at /usr/local. Your system Python will sill be the older version. You can invoke the old version using `python` or the newer one using `python2.7` directly into your console.

You can check if everything is fine by issuing:

```
user@server [~]# python -V
Python 2.6.6
user@server [~]# python2.7 -V
Python 2.7.6
user@server [~]# 
```

As you can see, the two versions are installed and working without conflicting with each other!

# Install PIP

```
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py --no-index --find-links=/local/copies # Maybe ignore this line... keep going if error.
python get-pip.py --user
pip install virtualenv
```

# Setup virtual env

A virtualenv works like a sandbox where you can run a specific version of Python with its own plugins. Its basically a folder. So, create a folder for your project like `~/projectFolder` and `cd` to it.

```
mkdir ~/projectFolder
cd ~/projectFolder
virtualenv -p /usr/local/bin/python2.7 ~/projectFolder
```

# Activate the virtualenv

```
source ~/projectFolder/bin/activate
```

Now your console should have the project name at the begging.

# Install Twistd and multi-socks

```
pip install Twisted
wget https://github.com/aivarsk/multi-socks/archive/master.zip
unzip master.zip
cp multi-socks-master/* . -R
python setup.py install
```

Now you can run multi-socks: `twistd multi-socks -a x.x.x.x:yy -w ip.txt`.
Once you're finished, you should exit the virtual env by issuing:

```
deactivate
```

**Please Note**: Every time you need to launch multi-socks, you really need to activate the virtual env by issuing:

```
cd /projectFolder
source ~/projectFolder/bin/activate
```

Only this way you'll be sure to be running the right version of Python.

**Warning**: Never ever consider replacing the system version of Python on CentOS or CloudLinux with the new version, this will break yum and a bunch of other system tools. Follow the steps I provided on how to install a different version and have them both.
